### ISSUE TITLE
List isn't being populated

### ISSUE THREAD

**Issue by forrestblade** [sveltejs/svelte-virtual-list#33]
Maybe I'm doing something wrong but basically I'm trying to create a virtual list of images after a fetch call.  It was working before without the virtual list but now it doesn't.  It doesn't seem to be populating the List.

Here is the code I am using, lemme know if I'm just an idiot or this is a real issue.
```js
<script>
  import VirtualList from '@sveltejs/svelte-virtual-list';

  export let results = [];
  $: results;
</script>

{#if results.length}
<VirtualList items={results} let:result>
  <div class="fl pa2 w-50 w-20-ns">
      <a href={result.url} class="db aspect-ratio aspect-ratio--1x1 dim">
        <div style="background-image: url('{result.images.original.url}')" class="bg-center cover aspect-ratio--object">
        </div>
      </a>
  </div>
</VirtualList>
{/if}
```

**Comment by apurvjain95** [comment]
Hey. Did you try to use 'let:item' instead of 'let:result'?
